name: Continuous Integration
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  # See: https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012
  push:
    branches:
      - master*
  pull_request:
    branches:
      - master*

jobs:
  build:
    name: Full Build (node ${{ matrix.node_version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 20.x
      # https://stackoverflow.com/questions/61070925/github-actions-disable-auto-cancel-when-job-fails
      fail-fast: false

    steps:
      # using `v1` because of: https://github.com/actions/checkout/issues/246
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Setup pnpm
        # pnpm version from package.json `packageManager` field is used
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run ci

#      - name: npm auth setup
#        run: |
#          npm logout || true
#          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
#          npm whoami
#        env:
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release Pull Request
        id: create_or_update_release_pr
        uses: changesets/action@v1
        # Changesets + `apps` may automatically create tags for 'apps' during PR builds, but this should only happen
        # after merge to master
        # - https://github.com/changesets/changesets/blob/main/docs/versioning-apps.md
        # - Our `private:true` packages (mainly VSIX) are treated as `apps` by changesets
        if: github.event_name != 'pull_request'
        with:
          title: "chore: version packages"
          commit: "chore: version packages"
          version: pnpm run ci:version
          publish: pnpm run ci:release
#        env:
          # See: https://github.com/changesets/action/issues/187#issuecomment-1228413850
#          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/github-script@v7
        env:
          #                A JSON array to present the published packages. The format is `[{"name": "@xx/xx", "version": "1.2.0"}, {"name": "@xx/xy", "version": "0.8.9"}]`
          pkgList: ${{steps.create_or_update_release_pr.outputs.publishedPackages}}
        with:
          #         TODO: run file not script directly
          #         TODO: how to test file directly?
          script: |
            const { pkgList } = process.env
            console.log(pkgList)   
